stages:
- stage: build
  jobs:
  - job: build
    pool: 
      vmImage: ubuntu-16.04
    steps:
    - use: node
      version: 10.x
    - script: npm install
    - script: npm test
    - script: zip -r app.zip .
    - upload: app.zip

- stage: staging
  dependsOn: build
  jobs:
  - deployment: deploy-to-staging
    environment: contoso-webapp-staging
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'node-app'
            appType: 'webAppLinux'
            appName: 'linuxmvptest19'
            runtimeStack: 'NODE|10.1'
            startUpCommand: 'npm run start'

- stage: prod
  dependsOn: staging
  jobs:
  - deployment: deploy-to-prod
    environment: contoso-webapp-prod
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'node-app-parallel'
            appType: 'webAppLinux'
            appName: 'linuxparalleltest19'
            runtimeStack: 'NODE|10.1'
            startUpCommand: 'npm run start'
